// import "./javascript-homeworks/homework-2.1/alert.js"
// import "./javascript-homeworks/homework-2.4/task-1.js"
// import "./javascript-homeworks/homework-2.4/task-2.js"
// import "./javascript-homeworks/homework-2.4/task-3.js"
// import "./javascript-homeworks/homework-2.5/task-1.js"
// import "./javascript-homeworks/homework-2.6/task-1.js"
// import "./javascript-homeworks/homework-2.8/task-1.js"
// import "./javascript-homeworks/homework-2.8/task-2.js"
// import "./javascript-homeworks/homework-2.8/task-3.js"
import "./javascript-homeworks/homework-2.8/task-4.js"